### ISSUE TITLE
Mulitlanguage/Multisite: Custom meta not updating

### ISSUE THREAD

**Issue by eugster** [cnj-digital/seotamic#98]
When custom meta is set (e.g. title) and I'm switching from one site of a multisite installation to another, the content of the meta is not updated to the new language.

Also when setting a new custom meta, the chain icon does not break and the entered data is not saved. 
The only way to save a translation is manually breaking the chain icon and then entering the new meta.

**Comment by martink635** [comment]
Thanks for opening this issue!

Is this present on the latest version? I think this was fixed in the latest update `v5.0.2`, that was released a couple days ago.

**Comment by eugster** [comment]
Yes, it is still present in v.5.0.2.

First thing i did, was updating SEOtamic to check if it' has been fixed.

What seems to have been fixed is, that the chain-icon does display a "broken" state when clicked. This was not the case with v.5.0.0 I had installed before.

**Comment by eugster** [comment]
Sorry, I haven't been able to test before today.

How would i use the master branch in a test environment? Just download it and replace the files in vendor/cnj/seotamic with the content of the repo?

If yes, it did not fix my issue.

**Comment by martink635** [comment]
The easiest way is to set the version to `dev-master` in `composer.json`

If that does not fix anything please provide some more information (screen recording, github repo) since I don't think I can reproduce it in the latest development version.

**Comment by eugster** [comment]
Thanks for your help.

I've installed the dev-master and did test again. Sadly no change. 

- This video shows what happens when I change language and just edit the custom title. This reverts the edit I did on the title. When editing the the tile the chain icon does not change.
https://github.com/user-attachments/assets/4730a8b5-1838-4660-b9b7-530a62978479

- This video shows what happens when clicking on the chain icon.
https://github.com/user-attachments/assets/3a64bebc-2da5-4b2e-beee-66204a51955e

- This video shows how a default Statamic field behaves when editing the translation. As soon as there's an input it changes from linked to broken.
https://github.com/user-attachments/assets/c0e80b72-27d6-4712-9358-b91b622e3ca8

I hope this helps finding the problem.

**Comment by martink635** [comment]
Let me know if this is still an issue!
